import latest from "@/data/whoop/latest.json";

// Trends + the sleep→recovery insight, generated by my life-os from its store
// (`bun run whoop:snapshot`). Sits under the Whoop rings to add context to today.
export function LifeOsHealth() {
  const { trends, insight } = latest;
  return (
    <div className="mt-5 space-y-3 border-t border-border/50 pt-4">
      <p className="font-mono text-xs text-muted-foreground tabular-nums">
        {trends.days}-day avg · Recovery {trends.avgRecovery} · Sleep {trends.avgSleep}h ·{" "}
        {trends.workouts} workouts
      </p>
      {insight.enough && insight.sleepDelta != null && (
        <p className="max-w-[65ch] text-sm leading-relaxed text-muted-foreground">
          Sleep is my recovery lever: nights of 7h+ average{" "}
          <span className="font-medium text-brand">{insight.afterGood}</span> recovery vs{" "}
          <span className="font-medium text-brand">{insight.afterShort}</span> after short ones — a{" "}
          <span className="font-mono">
            {insight.sleepDelta > 0 ? "+" : ""}
            {insight.sleepDelta}
          </span>{" "}
          swing, surfaced by my{" "}
          <a
            href="/now"
            className="underline underline-offset-2 hover:text-brand transition-colors"
          >
            life-os
          </a>
          .
        </p>
      )}
    </div>
  );
}
